---
language: python
services: docker
python:
  - "2.7"

env:
  global:
    - MY_PATH: "~/Library/Application\ Support/Dash/DocSets/Redbeard28"
  matrix:
    - TYPE_TO_GENERATE: serve
    - TYPE_TO_GENERATE: html

before_install:
  - mkdir -p ~/Library/Application\ Support/Dash/DocSets/Redbeard28
  -

install:
  - pip install molecule docker molecule[docker]

script:
  - ./generate_doc.sh -d /tmp/docset -D . -i "redbeard28/docset:1.0" -m $TYPE_TO_GENERATE -P $MY_PATH

