site_name: Redbeard-Consulting docs
site_url: http://redbeard-consulting_docs.redthedocs.io
site_description: Base de connaissances documentaire provenant d'un consultant freelance Linux
site_autor: Jérémie CUADRADO
site_favicon: images/favicon.ico

pages:
  - ['index.md', 'Home']
  - ['howto/mkdocs/utilisation_markdown.md', 'Markdown', 'How to use markdown']
theme: readthedocs