# Project information
site_name: 'Redbeard-consulting documentation'
site_description: 'A collection of cheatsheets and code snippets.'
site_author: 'Jeremie CUADRADO'
site_url: 'http://cheatsheets.redbeard-consulting.fr/'

# Repository
repo_name: 'redbeard28/cheatsheets'
repo_url: 'https://github.com/redbeard28/cheatsheets'
edit_uri: edit/master/docs_src/

# Copyright
copyright: 'Copyright &copy; 2017-2019 Jeremie CUADRADO'

# Documentation sources and theme
docs_dir: 'docs_src'
site_dir: 'docs'

theme:
  name: material
  palette:
    primary: 'deep blue'
    accent: 'blue'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
#  feature:
#    tabs: true
# logo: 'images/logo.svg'
# favicon: 'assets/images/favicon.ico

# Options
extra:
  social:
    - type: 'github'
      link: 'https://github.com/redbeard28'
    - type: 'twitter'
      link: 'https://twitter.com/redbeardjcu'
    - type: 'linkedin'
      link: 'https://www.linkedin.com/in/jeremiecuadrado/'
    - type: 'instagram'
      link: 'https://www.instagram.com/redbeard28/'
    - type: 'instagram'
      link: 'https://www.instagram.com/3dfabric/'
    - type: 'youtube'
      link: 'https://www.youtube.com/channel/UCySAJzbi3pZS8FFx19SKXiQ'

#  disqus: 'your-shortname'


# Google Analytics
google_analytics:
  - 'UA-89297097-1'
  - 'auto'

# Extensions
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true