site_name: Redbeard-Consulting docs
site_url: http://docs.redbeard-consulting.fr
repo_url: https://github.com/redbeard28/redbeard-consulting_docs
site_description: Base de connaissances documentaire provenant d'un consultant freelance Linux
site_autor: Jérémie CUADRADO
site_favicon: 'images/favicon.ico'
theme: 'readthedocs'
markdown_extensions: 
  - fenced_code
  - admonition
  - codehilite(css_class=code)
extra:
  version: '0.1.0'
  logo: 'images/redbeardv4_LOGO.jpg'
  palette:
    primary: 'light blue'
    accent: 'blue'
google_analytics:
  - 'UA-89297097-1'
  - 'auto'

pages:
- ['index.md', 'Accueil']
- ['howto/mkdocs/utilisation_markdown.md', 'Markdown', 'How to use markdown']
- ['aws/freenas_aws_s3.md', 'Cloud Amazon', 'Backup sync with s3cmd on AWS S3 bucket']
- ['howto/ansible/ansible_howto.md', 'Howto', 'Ansible basics commands']
- ['howto/Linux/populate-hosts.deny.md', 'Howto', 'Populate file hosts.deny']
- ['howto/keepalived/install_keepalived.md', 'Howto', 'Howto install keepalived']
- ['howto/keepalived/configure_keepalived.md', 'Howto', 'Howto configure keepalived']
- ['howto/keepalived/verify_keepalived.md', 'Howto', 'Howto verify keepalived']
- ['howto/Red Hat/register-redhat-system.md', 'Howto', 'Register and subscribe a redhat system']
- ['howto/Red Hat/yum_error_erno-3.md', 'Howto', 'yum error [erno-3]']
- ['shell-bash/date-avanced-cmd.md', 'Shell/Bash', 'Utilisation avancée de la commande date']
- ['shell-bash/freeze-by-cpu-overload.md', 'Shell/Bash', 'Freeze server by cpu overload']
- ['shell-bash/kill-zombie-process.md', 'Shell/Bash', 'Kill that zombie processus']
- ['shell-bash/most-use-cmd-list.md', 'Shell/Bash', 'Liste des commandes les plus utilisées']
- ['shell-bash/cmd-grep.md', 'Shell/Bash', 'Exemples de commandes grep']
- ['shell-bash/find-rm.md', 'Shell/Bash', 'Delete Files older than']
- ['shell-bash/folder-proc.md', 'Shell/Bash', 'Le répertoire /proc']
- ['shell-bash/reverse-ssh-tunel.md', 'Shell/Bash', 'Reverse SSH Tunnel']
- ['domotique/domoticz/create-dummy-switch.md', 'Domotique', 'Créer un switch virtuel']
- ['domotique/domoticz/sonos-integration.md', 'Domotique', 'Intégrer Sonos à domoticz']
- ['domotique/domoticz/tts-domoticz.md', 'Domotique', 'Mettre en place du TTS sous domoticz']
- ['about/license.md', 'About', 'License']
- ['about/release-notes.md', 'About', 'Release Notes']
