site_name: Redbeard-Consulting docs
site_url: http://redbeard-consulting_docs.redthedocs.io
site_autor: Jérémie CUADRADO
site_favicon: images/favicon.ico
theme: readthedocs

pages:
  - [ 'index.md', 'Home' ]
  - [ 'howto/mkdocs/utilisation_markdown.md', 'Markdown', 'How to use markdown' ]
